### ISSUE TITLE
installer v0.2.3 error: Java Home not found

### ISSUE THREAD

**Issue by astroman133** [microsoft/vscode-java-pack#351]
I get the following error installing the Visual Studio Code Java Pack Installer. This is a MS installer!

installer version: 0.2.3
env:
```
os: win32
arch: x64
PATH: C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\AOMEI Backupper;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files (x86)\NTP\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Users\Rick\AppData\Local\Microsoft\WindowsApps;C:\Program Files\CMake\bin;C:\Users\Rick\AppData\Local\Programs\Microsoft VS Code\bin;
JAVA_HOME: C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\
JDK_HOME: C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\
```
log:
```
[11:49:03 AM] Download JDK
[11:52:38 AM] Download JDK ... [Completed]
[11:52:38 AM] Install JDK
[11:53:28 AM] Install JDK ... [Completed]
[11:53:28 AM] Configure Java Settings
[11:53:28 AM] Error occurred
[11:53:28 AM] Java Home not found.

```

**Comment by Eskibear** [comment]
This installer depends on [node-find-java-home](https://github.com/jsdevel/node-find-java-home) to detect your installed JDK. Could you find and attach file `%TEMP%\vscode-java-installer\log.txt`?

**Comment by astroman133** [comment]
The requested log file is attached.

[log.txt](https://github.com/microsoft/vscode-java-pack/files/4424430/log.txt)

**Comment by Eskibear** [comment]
Thanks for the log. It helps a lot. The command to check JDK version is broken for your machine, and I guess that would be the same for many other users who have the same error.

The log indicates some of your actions (correct me if wrong):
- You have JDK 14 installed before running this installer for the first time, but you didn't proceed to install it. 
- The second time you run it, JDK 14 was not detected (deleted?), thus it installed a default JDK (AdoptOpenJDK 11)  for you. (I'm wondering why it's installed in `Program Files` folder instead of `%USERPROFILE%\AppData\Local\Programs` which is specified by our installer.)  But after installation, during configuring step later, it failed to check the version because of below error.
```
{
  "killed": false,
  "code": 1,
  "signal": null,
  "cmd": "C:\\Program Files\\AdoptOpenJDK\\jdk-11.0.6.10-hotspot\\/bin/java -version"
}
```
- And behind that I find some trace that you manually removed vscode and jdk, and re-run the installer serval times?

**Comment by astroman133** [comment]
Your interpretation of the log seems correct. How to I fix it?
Thanks!

**Comment by Eskibear** [comment]
I'm afraid there's no workaround for the moment, because [Language support for Java](https://github.com/redhat-developer/vscode-java) is using the same code to check java version. 

This installer does below things for you:
- [**done**] install vscode if not installed
- [**done**] install jdk if you don't have one
- [**error**] detect and configure `java.home` in vscode's settings, to ensure [Language support for Java](https://github.com/redhat-developer/vscode-java) can be successfully launched.
- [**can be done manually**] install Java extension pack for your vscode

Step 3&4 can be manually done, you can set `java.home` setting in your vscode, and  you can also install the extension pack in vscode's extensions panel. As [Language support for Java](https://github.com/redhat-developer/vscode-java) suffers from the same issue, it's possibly not working. But I suggest you to give it a try, and **let us know the result.** 

I imagine that, you can try setting value of `java.home` to `C:\\Program Files\\AdoptOpenJDK\\jdk-11.0.6.10-hotspot`, **no trailing slash "\\"**.  So the java binary path will be resolved as `C:\\Program Files\\AdoptOpenJDK\\jdk-11.0.6.10-hotspot/bin/java` instead of the `balabala\\/bin/java`.  Maybe it will work it around.

**Comment by Eskibear** [comment]
we've improved the way of JDK recognition, in both installer and upstream projects. It should be fixed.

**Comment by pcantrell** [comment]
I have multiple students still getting this error, apparently for this reason, as of this week. Will investigate and try to reproduce.

**Comment by Eskibear** [comment]
@pcantrell Thanks for reporting, and we are aware that some people are getting the same error (but for different reasons). It would be very helpful if you find a way to reproduce it, and provide detailed logs. 
Please track this issue in https://github.com/microsoft/vscode-java-installer/issues/53 .

**Comment by pcantrell** [comment]
Confirmed that this is occurring for some students in the class I’m teaching:

- This extension fails to detect AdoptOpenJDK, installed at `C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot` or similar,
- `java.home` is not set in the VS Code `settings.json`, and
- setting `java.home` manually fixes the problem.

**However,** when I do a clean install on a clean Windows VM, the VS Code extension detects a fresh AdoptOpenJDK installation just fine. I haven't yet managed to figure out why auto-detection doesn't happen on some students’ machines.

Would you like me to open a fresh issue for this, even though I don't have more definitive info?

**Comment by Eskibear** [comment]
Good finding, and it's imilar with what the log reveals in https://github.com/microsoft/vscode-java-installer/issues/53#issuecomment-683832774 

We do pass `INSTALLDIR=C:\Users\<username>\AppData\Local\Programs\AdoptOpenJDK` to the MSI installer, but somehow  it's installed at `C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot`. I guess that is a clue. 

BTW, detailed logs can be found at `%TEMP%\vscode-java-installer\log.txt` and `%TEMP%\AdoptOpenJDK-MSI.log`, and let's continue the discussion in https://github.com/microsoft/vscode-java-installer/issues/53 .
